-- ============================================================
-- ID採番レース条件の解消(冪等版・何度実行しても安全)
-- links / records の id を JS側「MAX(id)+1」計算からDB側自動採番へ移行し、
-- 自然キーのUNIQUE制約でDBに重複防止を保証させる。
--
-- 実際のスキーマを確認したところ:
--   - records.id は bigint (デフォルトなし) → IDENTITY化が可能で、既に成功済み
--   - links.id   は text   (デフォルトなし) → IDENTITY(整数専用)は使えないため、
--                                             gen_random_uuid()::text をデフォルトにする方式に変更
--     ※ アプリ側は link.id を単なる不透明な文字列として扱っており、数値である
--        ことに依存している箇所は無いため、UUID文字列に変えても影響はない
--
-- 適用手順:
--   1. Supabaseダッシュボード > SQL Editor でこのファイルの内容を実行する
--      (前回の実行が途中で失敗していても、このバージョンは
--       「すでに存在する場合はスキップ」するので再実行してOK)
--   2. 実行後に index.html（このコミット以降のバージョン）をデプロイする
--      ※ 順序が逆だと、新しいアプリコードが未対応のDBに対して
--        onConflict: 'program_id,name' 等を指定してエラーになる
--   3. 実行後、末尾の確認クエリの結果を見て、両テーブルとも
--      自動採番が設定されているか確認する
-- ============================================================

-- 1. 自然キーにUNIQUE制約を追加
--    (同一大会内で同名リンクの重複、同一リンク×フェーズのレコード重複をDBが禁止する)
-- UNIQUE制約は内部的に同名のインデックスも作るため、名前衝突時は
-- duplicate_object(42710)ではなく duplicate_table(42P07)で返ってくる点に注意
DO $$
BEGIN
    ALTER TABLE links ADD CONSTRAINT links_program_id_name_key UNIQUE (program_id, name);
EXCEPTION
    WHEN duplicate_object OR duplicate_table THEN
        RAISE NOTICE 'links_program_id_name_key は既に存在するためスキップしました';
END $$;

DO $$
BEGIN
    ALTER TABLE records ADD CONSTRAINT records_program_id_link_id_phase_key UNIQUE (program_id, link_id, phase);
EXCEPTION
    WHEN duplicate_object OR duplicate_table THEN
        RAISE NOTICE 'records_program_id_link_id_phase_key は既に存在するためスキップしました';
END $$;

-- 2. id列をDB側自動採番に変更
-- links.id は text 型なので、IDENTITYではなくUUID文字列を生成するデフォルト式を設定する
-- (ALTER COLUMN ... SET DEFAULT は何度実行しても安全なので例外処理は不要)
ALTER TABLE links ALTER COLUMN id SET DEFAULT gen_random_uuid()::text;

-- records.id は bigint 型なので、SQL標準のIDENTITY列に変更する
DO $$
BEGIN
    ALTER TABLE records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
EXCEPTION
    WHEN others THEN
        RAISE NOTICE 'records.id の identity化はスキップしました(既に設定済みの可能性): %', SQLERRM;
END $$;

-- 3. records.id の既存データの最大値からシーケンスを継続させる(何度実行しても安全)
--    (links.id はシーケンスを使わない方式のためここでは対象外)
DO $$
BEGIN
    IF pg_get_serial_sequence('records', 'id') IS NOT NULL THEN
        PERFORM setval(pg_get_serial_sequence('records', 'id'), COALESCE((SELECT MAX(id) FROM records), 1));
    END IF;
END $$;

-- ============================================================
-- 4. 適用結果の確認(実行後にこの2つを流して結果を見てください)
-- ============================================================
-- 制約が両方とも存在するか
SELECT conname FROM pg_constraint
WHERE conname IN ('links_program_id_name_key', 'records_program_id_link_id_phase_key');

-- links.id はデフォルト式に gen_random_uuid() が入っているか、
-- records.id は is_identity が YES になっているか
SELECT table_name, column_name, column_default, is_identity, identity_generation
FROM information_schema.columns
WHERE table_name IN ('links', 'records') AND column_name = 'id';
